### ISSUE TITLE
gitlab CI test multiple versions

### ISSUE THREAD

**Issue by goretkin** [tpapp/PkgSkeleton.jl#22]
The travis CI template tests multiple versions of julia. I haven't tried it, but it seems possible with gitlab too:

https://forum.gitlab.com/t/testing-with-all-version-combinations-of-python-django/7408/3

**Comment by goretkin** [comment]
PkgTemplates#master does

```yaml
.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
Julia 1.3:
  image: julia:1.3
  extends:
    - .script
    - .coverage
Julia 1.4rc:
  image: julia:1.4.0-rc1-buster
  extends:
    - .script
    - .coverage

```
